language: nix
nix: 2.2.2
sudo: false
env:
  global:
  - CACHIX_CACHE=sticker
  - NUR_REPO=sticker
  - secure: wev0hKu4bmbT1L7WODPNgR4zvMB8DyQDCkN3Y4vlFTlDsaQFwlb5FD2AcIqCGeDDcBApSnCNXgVQWyC8I5/vO3k0bU8Mm4TPYPrmq9jh5msNnDB8W8ADDMvoqhRW50ePZT0YcssBSDIFdTSUQFkJKtCZey9d9mJgPSR/BjfbQXdIznYyqM3R5dInHmcuMluC/FJjGkRcFIEcc/uGB8eYz59QTdapIAYh3zCWxThkFjDkLehhpEIpDRIi6ZUXkEc0YIsfwT6IS+aL9QEgR2J1nGzrIV7xj1uLIJG0yIYqmi2ztN+BiTu4kOAVtjYN81C5RfpPHp3zSLuEW8XWAOlFCaqIynooQFL3jbXritqN1RTvfRR5dWo05QiVgrjwxXSjEhwWPC4G8aWtbah5WRpZBYPJzqQQJiERRytNXzBwNeb8HifxUKfN4OIZZkg/gFSd15vuS/yVfFl2rEvKCmJkPqIRUNpG+qCpNfpmCA5m+MhPxI333XYLiVy9M6BtthJybC+zQn5AT962DHUGS+bQMK/tf/qRBQ9sAG679CVOl0SvBiLto8LB6p/sbujMrOHvtHcJEpeLXuy3hwKM5QL5JTmII5ls/sbd2yqFVE/0ypzrW6dIjAUhCxdDYmSPyYhhQIYuZokWd5KIbThJHP2gh4RAingfzRgDGMOxUSK8yeI=
  - secure: kJ0RuWGdLZRZve7wR0GCs5609t5AXLtBUHxT08Ov+XREGCHM+zhfN9djcOkk0aMpxgqLxEhiVgZXIqZ1whiHA4ps/OuolslswStm22qFA/+8Do5n1b3XeeF4CU+qeVaVtV5zu4FD0L23RMllUTDGKLZq59YwJmwl84eZuapbwpzzHki/n5nrL9TQluDF5aeDmIi4DPRkUWU9BbFzEcHSTN6N9vINtqt/8H0Df2lv6WJwc4RiWwkQm5/ZuIyLctp+R+zelBIiVxy4CXLcuj1YvoFR9cEbq+uJbDMfhx0pXuXyOdF7qHr1xz3X6htGIazG/S0oZyPwQ0RAAMzgLVqqU6YqX0tWAgGXMIo/HueDBhkcuXoX2FzMRVHakbqPfdtdIRXwmpuCSoelsHRIRuuWbpjnGYTTe5J+5uPnppD3qTogxrqz6o3AsOajYKkVc5H4OyBf14IC19dlg9SYEI4I7ftT8iK+Il2ikcgCGrPXOF4Q+MPbhOy/prCncD2OTxWXeVnlSycIdRrJox0qBsosDkbYUS2iIe/S+A6i/4M0XIgnhK/6B8v+Dpq1NdNHFeMj53u9e4qGtQgjm3KAkzekKBCsyO0HVlPre/sM73+t1szJVQtStPWcZQ8gzj1iaLzhxOnBG3sHn8nlL6FxctJd9vJBz/er1pjUjeOxuGFgomU=
matrix:
  include:
  - env: NIX_CHANNEL=https://nixos.org/channels/nixpkgs-unstable
  - env: NIX_CHANNEL=https://nixos.org/channels/nixos-unstable
  - env: NIX_CHANNEL=https://nixos.org/channels/nixos-19.09
install:
- nix --version
- sudo mkdir /etc/nix && echo 'sandbox = true' | sudo tee /etc/nix/nix.conf
- if [ -n "${CACHIX_CACHE}" ]; then travis_retry nix-channel --update; fi
- if [ -n "${CACHIX_CACHE}" ]; then nix-env -iA cachix -f https://cachix.org/api/v1/install;
  fi
- if [ -n "${CACHIX_CACHE}" ]; then cachix use "${CACHIX_CACHE}"; fi
- nix-channel --add "${NIX_CHANNEL}" nixpkgs
- travis_retry nix-channel --update
script:
- nix-build ci.nix -A buildOutputs
- nix eval -f default.nix 'lib'
- nix eval -f default.nix 'modules'
- nix eval -f default.nix 'overlays'
after_success:
- if [ -n "${CACHIX_CACHE}" ]; then nix-build ci.nix -A cacheOutputs | cachix push
  "${CACHIX_CACHE}"; fi
- if [ "false" = "${TRAVIS_PULL_REQUEST}" -a "master" = "${TRAVIS_BRANCH}" ]; then
  curl -XPOST "https://nur-update.herokuapp.com/update?repo=${NUR_REPO}"; fi
