name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        channel:
          - "https://nixos.org/channels/nixos-19.09"
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v7
    - run: nix-channel --add ${{ matrix.channel }} nixpkgs
    - run: nix-channel --update
    - run: cat /etc/nix/nix.conf
    - uses: cachix/cachix-action@v4
      with:
        name: sticker
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        file: ci.nix
        attributes: buildOutputs
    - run: nix eval -f default.nix 'lib'
    - run: nix eval -f default.nix 'modules'
    - run: nix eval -f default.nix 'overlays'
